export type LibraryExercise = { name: string; cat: string; target: string };

export const EXERCISE_CATEGORIES = [
  'Todos',
  'Peito',
  'Costas',
  'Pernas',
  'Ombro',
  'Bíceps',
  'Tríceps',
  'Abdômen',
  'Glúteos',
  'Panturrilha',
  'Cardio',
] as const;

export const EXERCISE_LIBRARY: LibraryExercise[] = [
  { name: 'Supino reto', cat: 'Peito', target: '4x10' },
  { name: 'Supino inclinado', cat: 'Peito', target: '4x10' },
  { name: 'Supino declinado', cat: 'Peito', target: '3x10' },
  { name: 'Supino com halteres', cat: 'Peito', target: '4x10' },
  { name: 'Supino inclinado com halteres', cat: 'Peito', target: '3x12' },
  { name: 'Crucifixo reto', cat: 'Peito', target: '3x12' },
  { name: 'Crucifixo inclinado', cat: 'Peito', target: '3x12' },
  { name: 'Crossover', cat: 'Peito', target: '3x15' },
  { name: 'Peck deck (voador)', cat: 'Peito', target: '3x15' },
  { name: 'Flexão de braço', cat: 'Peito', target: '3x15' },
  { name: 'Puxada frente', cat: 'Costas', target: '4x10' },
  { name: 'Puxada atrás', cat: 'Costas', target: '3x10' },
  { name: 'Puxada unilateral', cat: 'Costas', target: '3x12' },
  { name: 'Remada curvada', cat: 'Costas', target: '4x10' },
  { name: 'Remada cavalinho', cat: 'Costas', target: '3x10' },
  { name: 'Remada baixa (cabo)', cat: 'Costas', target: '3x12' },
  { name: 'Remada unilateral (halter)', cat: 'Costas', target: '3x12' },
  { name: 'Levantamento terra', cat: 'Costas', target: '4x8' },
  { name: 'Barra fixa', cat: 'Costas', target: '3x8' },
  { name: 'Pulldown', cat: 'Costas', target: '3x12' },
  { name: 'Agachamento livre', cat: 'Pernas', target: '4x10' },
  { name: 'Agachamento smith', cat: 'Pernas', target: '3x10' },
  { name: 'Agachamento frontal', cat: 'Pernas', target: '3x10' },
  { name: 'Agachamento sumô', cat: 'Pernas', target: '3x12' },
  { name: 'Agachamento búlgaro', cat: 'Pernas', target: '3x10' },
  { name: 'Leg press', cat: 'Pernas', target: '4x12' },
  { name: 'Hack squat', cat: 'Pernas', target: '3x10' },
  { name: 'Cadeira extensora', cat: 'Pernas', target: '3x15' },
  { name: 'Mesa flexora', cat: 'Pernas', target: '3x15' },
  { name: 'Cadeira flexora', cat: 'Pernas', target: '3x15' },
  { name: 'Stiff', cat: 'Pernas', target: '3x12' },
  { name: 'Levantamento terra romeno', cat: 'Pernas', target: '3x10' },
  { name: 'Afundo (avanço)', cat: 'Pernas', target: '3x12' },
  { name: 'Passada com halteres', cat: 'Pernas', target: '3x12' },
  { name: 'Desenvolvimento militar', cat: 'Ombro', target: '4x10' },
  { name: 'Desenvolvimento com halteres', cat: 'Ombro', target: '3x10' },
  { name: 'Desenvolvimento Arnold', cat: 'Ombro', target: '3x10' },
  { name: 'Elevação lateral', cat: 'Ombro', target: '3x15' },
  { name: 'Elevação frontal', cat: 'Ombro', target: '3x15' },
  { name: 'Elevação posterior (crucifixo invertido)', cat: 'Ombro', target: '3x15' },
  { name: 'Remada alta', cat: 'Ombro', target: '3x12' },
  { name: 'Encolhimento de ombros', cat: 'Ombro', target: '3x15' },
  { name: 'Face pull', cat: 'Ombro', target: '3x15' },
  { name: 'Desenvolvimento máquina', cat: 'Ombro', target: '3x12' },
  { name: 'Rosca direta', cat: 'Bíceps', target: '3x12' },
  { name: 'Rosca alternada', cat: 'Bíceps', target: '3x12' },
  { name: 'Rosca martelo', cat: 'Bíceps', target: '3x12' },
  { name: 'Rosca scott', cat: 'Bíceps', target: '3x12' },
  { name: 'Rosca concentrada', cat: 'Bíceps', target: '3x15' },
  { name: 'Rosca 21', cat: 'Bíceps', target: '3x21' },
  { name: 'Rosca cabo', cat: 'Bíceps', target: '3x15' },
  { name: 'Rosca inversa', cat: 'Bíceps', target: '3x12' },
  { name: 'Rosca no banco inclinado', cat: 'Bíceps', target: '3x12' },
  { name: 'Rosca punho', cat: 'Bíceps', target: '3x20' },
  { name: 'Tríceps corda', cat: 'Tríceps', target: '3x15' },
  { name: 'Tríceps testa', cat: 'Tríceps', target: '3x12' },
  { name: 'Tríceps francês', cat: 'Tríceps', target: '3x12' },
  { name: 'Tríceps coice', cat: 'Tríceps', target: '3x15' },
  { name: 'Tríceps banco (mergulho)', cat: 'Tríceps', target: '3x12' },
  { name: 'Tríceps pulley barra', cat: 'Tríceps', target: '3x15' },
  { name: 'Supino fechado', cat: 'Tríceps', target: '3x10' },
  { name: 'Tríceps unilateral cabo', cat: 'Tríceps', target: '3x15' },
  { name: 'Extensão de tríceps halter', cat: 'Tríceps', target: '3x12' },
  { name: 'Mergulho em paralelas', cat: 'Tríceps', target: '3x10' },
  { name: 'Abdominal', cat: 'Abdômen', target: '3x20' },
  { name: 'Abdominal infra', cat: 'Abdômen', target: '3x15' },
  { name: 'Abdominal bicicleta', cat: 'Abdômen', target: '3x20' },
  { name: 'Abdominal canivete', cat: 'Abdômen', target: '3x15' },
  { name: 'Abdominal com peso', cat: 'Abdômen', target: '3x15' },
  { name: 'Prancha', cat: 'Abdômen', target: '3x45s' },
  { name: 'Prancha lateral', cat: 'Abdômen', target: '3x30s' },
  { name: 'Elevação de pernas', cat: 'Abdômen', target: '3x15' },
  { name: 'Elevação de joelhos na barra', cat: 'Abdômen', target: '3x15' },
  { name: 'Abdominal máquina', cat: 'Abdômen', target: '3x15' },
  { name: 'Abdominal oblíquo', cat: 'Abdômen', target: '3x15' },
  { name: 'Ab wheel (roda abdominal)', cat: 'Abdômen', target: '3x10' },
  { name: 'Elevação pélvica', cat: 'Glúteos', target: '4x12' },
  { name: 'Glúteo four (quatro apoios)', cat: 'Glúteos', target: '3x15' },
  { name: 'Coice no cabo (glúteo)', cat: 'Glúteos', target: '3x15' },
  { name: 'Abdução de quadril', cat: 'Glúteos', target: '3x15' },
  { name: 'Agachamento sumô com halter', cat: 'Glúteos', target: '3x12' },
  { name: 'Step up', cat: 'Glúteos', target: '3x12' },
  { name: 'Glúteo máquina', cat: 'Glúteos', target: '3x15' },
  { name: 'Ponte de glúteo unilateral', cat: 'Glúteos', target: '3x12' },
  { name: 'Panturrilha em pé', cat: 'Panturrilha', target: '4x15' },
  { name: 'Panturrilha sentado', cat: 'Panturrilha', target: '3x15' },
  { name: 'Panturrilha no leg press', cat: 'Panturrilha', target: '3x15' },
  { name: 'Panturrilha unilateral', cat: 'Panturrilha', target: '3x15' },
  { name: 'Panturrilha smith', cat: 'Panturrilha', target: '3x15' },
  { name: 'Panturrilha burrinho', cat: 'Panturrilha', target: '3x15' },
  { name: 'Corrida na esteira', cat: 'Cardio', target: '20min' },
  { name: 'Bike ergométrica', cat: 'Cardio', target: '20min' },
  { name: 'Elíptico', cat: 'Cardio', target: '20min' },
  { name: 'Pular corda', cat: 'Cardio', target: '10min' },
  { name: 'Escada (stairmaster)', cat: 'Cardio', target: '15min' },
  { name: 'Remo ergométrico', cat: 'Cardio', target: '15min' },
  { name: 'HIIT', cat: 'Cardio', target: '15min' },
  { name: 'Corrida ao ar livre', cat: 'Cardio', target: '30min' },
  { name: 'Caminhada inclinada', cat: 'Cardio', target: '25min' },
  { name: 'Burpee', cat: 'Cardio', target: '3x15' },
];
